### ISSUE TITLE
Clicking on the About page crashes the site

### ISSUE THREAD

**Issue by felskia** [map-yemen/map-yemen.github.io#27]
If accessed through the Arabic version (i.e. Arabic > about> English) it works, otherwise not.

**Comment by felskia** [comment]
@dereklieu I was wondering if you could take a quick look at this and either point me in the right direction or tell me what's going on. This is the only real bug we have. When I click on about it doesn't do anything and this is the console error. 

<img width="1169" alt="screen shot 2017-11-22 at 5 29 49 pm" src="https://user-images.githubusercontent.com/5421566/33152468-c6a22e28-cfaa-11e7-977f-454df9d37377.png">

**Comment by dereklieu** [comment]
@felskia hey, it looks like the lack of any content following `- text` here is causing the issue:

https://github.com/map-yemen/map-yemen.github.io/blob/develop/app/assets/translations/about.yml#L6

Either removing that `-` block altogether or adding text similar to how the Arabic version is below will fix it. I'll also make a quick change so that this won't cause this to crash anymore.
