### ISSUE TITLE
Values aren't showing up on map

### ISSUE THREAD

**Issue by felskia** [map-yemen/map-yemen.github.io#39]
Newly added indicators at the governorate level appear under the "Add Indicators Overlay" tab, but once the indicator is selected and it loads, the entire map appears in one color despite the legend breakdown. Also, no values appear when different governorates are clicked on. For example, please see "Wheat Production - 2011", and attached screenshot.

@drewbo could this have to do with something you fixed on Map Egypt that just didn't transfer over here? Let me know what you think.

![capture](https://user-images.githubusercontent.com/5421566/33580601-d62b458a-d91b-11e7-9ce7-1b44742529d9.png)

**Comment by drewbo** [comment]
@felskia Is this an indicator created from CSV data or a mapbox id?

**Comment by felskia** [comment]
@drew It's created from a CSV. This is the path if you want to look at it: https://map-yemen.github.io/admin/#/indicators/44db5419-8331-4b77-b79d-c54a0c995ffd?_k=wad8co

**Comment by drewbo** [comment]
@felskia I think the data is entered incorrectly: the `data_geography` was set to Governorate but the ids are given at the district level. I changed the `data_geography` and things appear correctly (although most is still white because there isn't much data)

<img width="658" alt="screen shot 2017-12-06 at 12 26 01 pm" src="https://user-images.githubusercontent.com/7108211/33675509-cdc32398-da80-11e7-8a09-206052104dc6.png">
