### ISSUE TITLE
Names on popups (map page) for projects is not in arabic

### ISSUE THREAD

**Issue by felskia** [map-yemen/map-yemen.github.io#51]
obviously when you're on the arabic side of things

**Comment by dereklieu** [comment]
I think some of these are missing Arabic names in the data.

<img width="438" alt="screen shot 2018-01-07 at 9 27 27 pm" src="https://user-images.githubusercontent.com/1590802/34657160-995f2b1c-f3f1-11e7-9896-8b48440a1b62.png">

This one has an Arabic name ^^

<img width="357" alt="screen shot 2018-01-07 at 9 27 21 pm" src="https://user-images.githubusercontent.com/1590802/34657163-9db0ffd8-f3f1-11e7-8239-36c381eea6d2.png">

This one doesn't. I changed the default so that instead of showing the English name, it will show this message so that the operator can know to add the Arabic name.
