### ISSUE TITLE
For district indicator overlays the chart doesn't appear on the list/chart view

### ISSUE THREAD

**Issue by felskia** [map-yemen/map-yemen.github.io#6]
For this data, there is no chart, just a blank space where it should be.

@DylanMoriarty could you fix this today?

**Comment by DylanMoriarty** [comment]
@felskia for the district indicator there are 333 fields vs. the 19 we see when you're looking at the governants. It doesn't look like there's anything in the code to handle this, so drawing it currently looks like this:

![f-3](https://cloud.githubusercontent.com/assets/9341928/23618572/b83c063e-025e-11e7-809b-4451849a1ea4.jpg)

It looks like it's not displaying because Sprint-Nick put in a short circuit that creates an empty container if the data was too long.

Is fixing this via increasing the height of the chart to match the height of the data an alright solution for you?

**Comment by felskia** [comment]
@DylanMoriarty yes, that sounds good.

**Comment by felskia** [comment]
Also, for tickets if you could add me as a reviewer, just so that I can see that they are done would be helpful. 

Thanks!
